#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pkill tint2

bspc config focus_follows_pointer       true
bspc config history_aware_focus         true
bspc config focused_border_color        "#8AB4F8"
bspc config normal_border_color         "#242424"
bspc config presel_feedback_color       "#8AB4F8"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Screenkey manage=off
bspc rule -a Kupfer.py focus=on

setbg &
picom --experimental-backend --config ~/.config/picom/picomrc &
tint2 &
kupfer --no-splash &
unclutter --timeout 4 --ignore-scrolling &
i3-lock --image=~/.local/share/bg-blur -k
dunst &
