#!/bin/sh
# super + {_,shift + } Return
#  {xfce4-terminal,~/.local/bin/bspwm/scratchpad}

# super + grave
#   ~/.local/bin/bspwm/next-desktop

# super + shift + grave
#   ~/.local/bin/bspwm/move-blank-desktop

super + {_,shift + } grave
  ~/.local/bin/bspwm/next-desktop-sticky-plank {next,prev}

# super + shift + grave
#   ~/.local/bin/bspwm/move-blank-desktop-sticky-plank

# super + {_,shift + } Tab
#   ~/.local/bin/bspwm/tab-cycle-window {next,prev}
   
super + {_,shift + } Tab
  bspc node -f {next,prev}.!hidden.window

# super + {h,j,k,l}
# 	~/.local/bin/bspwm/switch-window {west,south,north,east}

super + {h,j,k,l}
	bspc node -f {west,south,north,east}
  
super + shift + {h,j,k,l}
  ~/.local/bin/bspwm/move-window {left,down,up,right}

super + f
  ~/.local/bin/bspwm/node-monocle

super + shift + F
  ~/.local/bin/bspwm/node-fullscreen

super + d
  ~/.local/bin/bspwm/node-floating

super + v
  ~/.local/bin/bspwm/show-clipman

super + {_,shift + }q
	~/.local/bin/bspwm/quit-node {c,k}

##

Print
  xfce4-screenshooter -f --clipboard

shift + Print
  xfce4-screenshooter -r --clipboard

ctrl + Print
   xfce4-screenshooter -f --save ~/Pictures/Screenshots
 
ctrl + shift + Print
  xfce4-screenshooter -r --save ~/Pictures/Screenshots

super + Print
  xfce4-screenshooter

super + alt + Print
  peek

super + Down
  sh -c "sleep 1 ; xdotool key XF86AudioPlay"

super + Left
  sh -c "sleep 1 ; xdotool key XF86AudioPrev"

super + Right
  sh -c "sleep 1 ; xdotool key XF86AudioNext"

super + Delete
	light-locker-command -l

super + r
	kupfer

super + b
  ps -C plank > /dev/null && pkill plank || plank
  
super + Escape
	pkill -USR1 -x sxhkd

super + {s,e,a}
  jumpapp {chromium,thunar,mousepad}

super + backslash
  ~/.local/bin/bspwm/scratchpad

super + shift + {s,e,a}
  /usr/bin/{chromium,thunar,mousepad}

super + Return
  /usr/bin/xfce4-terminal

super + shift + Return
  jumpapp xfce4-terminal

super + bracket{left,right}
	bspc desktop -f {prev,next}.local

super + shift + bracket{left,right}
  bspc node -d {prev,next}.local --follow;

super + alt + {q,r}
	bspc {quit,wm -r}

super + g
	bspc node -s biggest.window

super + {_,shift + }{1-6}
	bspc {desktop -f,node -d} '^{1-6}'

super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

super + ctrl + space
	bspc node -p cancel

super + alt + {h,j,k,l}
  n=20; \
  { d1=left;   d2=right;  dx=-$n; dy=0;   \
  , d1=bottom; d2=top;    dx=0;   dy=$n;  \
  , d1=top;    d2=bottom; dx=0;   dy=-$n; \
  , d1=right;  d2=left;   dx=$n;  dy=0;   \
  }\
  bspc node --resize $d1 $dx $dy || bspc node --resize $d2 $dx $dy

super + alt + shift + {l,k,j,h}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}
